name: Arduino Library CI

on: [pull_request, push, repository_dispatch]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # these are defined in this fine https://github.com/adafruit/ci-arduino/blob/master/build_platform.py#L34
        # under "ALL_PLATFORMS", also make sure that "BSP_URLS" also contains the board support info!
        arduino-platform: ["uno", "leonardo", "mega2560", "zero"]

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/checkout@v2
    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

    # manually install OctoWS2811
    - name: extra libraries
      run: |
        git clone --quiet https://github.com/PaulStoffregen/OctoWS2811.git /home/runner/Arduino/libraries/OctoWS2811

    - name: test platforms
      run: python3 ci/build_platform.py ${{ matrix.arduino-platform }}

  clang_and_doxy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - uses: actions/checkout@v2

    - uses: actions/checkout@v2
      with:
         repository: adafruit/ci-arduino
         path: ci

    - name: pre-install
      run: bash ci/actions_install.sh

